### ISSUE TITLE
`!!!` is deprecated, you must now use `doctype`

### ISSUE THREAD

**Issue by snowdream** [rbeere/i18next-jade-express-sample#5]
``` js
Error: d:\workspace\snowdream\test\i18next-jade-express-sample\views\layout.jade:1
  > 1| !!!5
    2| html
    3|   head
    4|     title #{title}

`!!!` is deprecated, you must now use `doctype`
    at Object.Lexer.doctype (d:\workspace\snowdream\test\i18next-jade-express-sample\node_modules\jade\lib\lexer.js:253:13)
    at Object.Lexer.next (d:\workspace\snowdream\test\i18next-jade-express-sample\node_modules\jade\lib\lexer.js:904:15)
    at Object.Lexer.lookahead (d:\workspace\snowdream\test\i18next-jade-express-sample\node_modules\jade\lib\lexer.js:113:46)
    at Parser.lookahead (d:\workspace\snowdream\test\i18next-jade-express-sample\node_modules\jade\lib\parser.js:102:23)
    at Parser.peek (d:\workspace\snowdream\test\i18next-jade-express-sample\node_modules\jade\lib\parser.js:79:17)
    at Parser.parse (d:\workspace\snowdream\test\i18next-jade-express-sample\node_modules\jade\lib\parser.js:117:26)
    at Parser.parse (d:\workspace\snowdream\test\i18next-jade-express-sample\node_modules\jade\lib\parser.js:131:24)
    at parse (d:\workspace\snowdream\test\i18next-jade-express-sample\node_modules\jade\lib\index.js:102:21)
    at Object.exports.compile (d:\workspace\snowdream\test\i18next-jade-express-sample\node_modules\jade\lib\index.js:172:16)
    at Object.exports.render (d:\workspace\snowdream\test\i18next-jade-express-sample\node_modules\jade\lib\index.js:310:15)
```

**Comment by snowdream** [comment]
merge my pull request to solve it ,please.
